version: '3'
services:
  stubby:
    image: "mvance/stubby:latest"
    networks:
     - dns
    volumes:
     - ./stubby/stubby.yml:/opt/stubby/etc/stubby/stubby.yml:ro
    environment:
     - TZ
    restart: unless-stopped
  unbound:
    image: "mvance/unbound:1.20.0-stubby"
    depends_on:
      - "stubby"    
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    networks:
     - dns
    volumes:
     - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    environment:
     - TZ
    restart: unless-stopped

networks:
  dns:
